# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Espejote < Formula
  desc "An in-cluster templating controller."
  homepage "https://github.com/vshn/espejote"
  version "0.15.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vshn/espejote/releases/download/v0.15.1/espejote_0.15.1_darwin_amd64.tar.gz"
      sha256 "ce9442e34615d2b271d0ce7283a22519ef5d234fb47cafb8f881de25e7681cb0"

      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vshn/espejote/releases/download/v0.15.1/espejote_0.15.1_darwin_arm64.tar.gz"
      sha256 "991657e95a6e36fd9bc084f1051698e8dd6ac293e4bc25a213994a0885f4c74f"

      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshn/espejote/releases/download/v0.15.1/espejote_0.15.1_linux_amd64.tar.gz"
      sha256 "21f534c73128cf90aea9c7265439d0c62acdf55cd8659cd10b911e16bbade905"
      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshn/espejote/releases/download/v0.15.1/espejote_0.15.1_linux_arm64.tar.gz"
      sha256 "20d717ee2292b2c859503925c6fe9e5bec3baf3343f777db697a773fcd488938"
      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
  end
end
