# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Espejote < Formula
  desc "An in-cluster templating controller."
  homepage "https://github.com/vshn/espejote"
  version "0.16.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vshn/espejote/releases/download/v0.16.0/espejote_0.16.0_darwin_amd64.tar.gz"
      sha256 "b6bd1eccaac9f19cbefa5d0ed1b1ed85f8e1bd6b972e4ee93901cabba30e2a37"

      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vshn/espejote/releases/download/v0.16.0/espejote_0.16.0_darwin_arm64.tar.gz"
      sha256 "f2622d32fc8801d7f0e24fca5736eeda5199c4d8bbe0ae05b56dfad59cef2fe4"

      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshn/espejote/releases/download/v0.16.0/espejote_0.16.0_linux_amd64.tar.gz"
      sha256 "b6ccc1e1432cc803eba7108a66d880ca76de47ea68860a9b42089e5297b21d5a"
      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshn/espejote/releases/download/v0.16.0/espejote_0.16.0_linux_arm64.tar.gz"
      sha256 "6aea76d18a231e3844aef99ffe846b4ff7add8df6e41265ba2d40aac25525c4b"
      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
  end
end
