# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Espejote < Formula
  desc "An in-cluster templating controller."
  homepage "https://github.com/vshn/espejote"
  version "0.14.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vshn/espejote/releases/download/v0.14.1/espejote_0.14.1_darwin_amd64.tar.gz"
      sha256 "6768c450969c372d8600c72d37cfc033f11df91e9312926e976a63c9bff9fef5"

      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vshn/espejote/releases/download/v0.14.1/espejote_0.14.1_darwin_arm64.tar.gz"
      sha256 "fb3dc622dc564ac460bdc6478a3c9d509b753d451f881df4a87716d76c686899"

      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshn/espejote/releases/download/v0.14.1/espejote_0.14.1_linux_amd64.tar.gz"
      sha256 "a7499fe447c516a7090e147282f0fda6d12c6c366eee4ffb1a043f4140549748"
      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vshn/espejote/releases/download/v0.14.1/espejote_0.14.1_linux_arm64.tar.gz"
      sha256 "37c2c94169c974804465922bb2618f23fe9bf0418b0c1c1353cc940c6e55dcce"
      def install
        bin.install "espejote"
        bash_completion.install "contrib/completion/bash/espejote"
        fish_completion.install "contrib/completion/fish/espejote"
        zsh_completion.install "contrib/completion/zsh/_espejote"
      end
    end
  end
end
